const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94775228949"
const SESSION_ID = "PRABATH-MD~qD4kmYLR#Y1FQeTVYiIgCdWzUFyfufEg7NwVfnMjHlnHhz6jjmqE"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
